### ISSUE TITLE
拉取配置失败

### ISSUE THREAD

**Issue by zhaocl2000** [2hacc/TVBox#40]
![7425bfc3502a57ddffdee6639d1bddf](https://github.com/2hacc/TVBox/assets/149944259/c73897da-73ee-4525-978c-249aa74657ba)
大佬，在安装后我还能正常使用，在用过一段时间后就出现如图的拉取配置失败的提示，我在手机上也试了tvbox，同样的设置手机上都能正常使用，电视上拉去配置失败，这咋弄？

**Comment by yichang99** [comment]
可能是存储权限问题发自我的手机-------- 原始邮件 --------发件人： zhaocl2000 ***@***.***>日期： 2024年2月12日周一 20:10收件人： 2hacc/TVBox ***@***.***>抄送： Subscribed ***@***.***>主    题： [2hacc/TVBox] 拉取配置失败 (Issue #40)
7425bfc3502a57ddffdee6639d1bddf.jpg (view on web)
大佬，在安装后我还能正常使用，在用过一段时间后就出现如图的拉取配置失败的提示，我在手机上也试了tvbox，同样的设置手机上都能正常使用，电视上拉去配置失败，这咋弄？
